import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'jsdom',
    setupFiles: ['tests/gsap.setup.ts'],
    exclude: ['tests/e2e/**', 'node_modules/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'html'],
      include: [
        'src/core/Game.ts',
        'src/core/GameScene.ts',
        'src/core/GameInputHandler.ts',
        'src/core/ContainerRenderer.ts',
        'src/core/PropsConfigLoader.ts',
        'src/core/AdManager.ts',
        'src/core/GameEffectManager.ts',
        'src/core/GameEventRouter.ts',
        'src/core/PropEffectHandler.ts',
        'src/core/GameStateMachine.ts',
        'src/core/LevelLoader.ts',
        'src/core/AudioManager.ts',
        'src/core/PhysicsManager.ts',
        'src/core/InputManager.ts',
        'src/core/SceneManager.ts',
        'src/core/SaveManager.ts',
        'src/core/TutorialManager.ts',
        'src/core/BlockPool.ts',
        'src/core/ObjectPool.ts',
        'src/gameplay/Block.ts',
        'src/gameplay/BlockPreview.ts',
        'src/gameplay/BlockSpawner.ts',
        'src/gameplay/Container.ts',
        'src/gameplay/PhysicsEntity.ts',
        'src/gameplay/ScoreSystem.ts',
        'src/gameplay/LevelSystem.ts',
        'src/gameplay/MergeSystem.ts',
        'src/gameplay/props/PropSystem.ts',
        'src/gameplay/props/BombProp.ts',
        'src/gameplay/props/FreezeProp.ts',
        'src/gameplay/props/LuckyProp.ts',
        'src/gameplay/props/RainbowProp.ts',
        'src/gameplay/props/ShrinkProp.ts',
        'src/ui/UIManager.ts',
        'src/ui/components/WarningLine.ts',
        'src/ui/components/ComboDisplay.ts',
        'src/ui/components/PropButton.ts',
        'src/ui/components/UIButton.ts',
        'src/ui/components/UIPanel.ts',
        'src/ui/components/UIProgressBar.ts',
        'src/ui/effects/ParticleEffect.ts',
        'src/ui/effects/MergeEffect.ts',
        'src/ui/effects/ExplosionEffect.ts',
        'src/ui/effects/FreezeEffect.ts',
        'src/ui/hud/GameHUD.ts',
        'src/ui/screens/MainMenuScreen.ts',
        'src/ui/screens/ResultScreen.ts',
        'src/ui/screens/LevelSelectScreen.ts',
        'src/ui/screens/PauseScreen.ts',
        'src/ui/screens/SettingsScreen.ts',
        'src/ui/screens/LoadingScreen.ts',
        'src/ui/TutorialOverlay.ts',
        'src/ui/layout/Layout.ts',
        'src/utils/EventBus.ts',
        'src/utils/PerformanceMonitor.ts',
        'src/utils/AnimationManager.ts',
        'src/platform/PlatformAdapter.ts',
      ],
      thresholds: {
        lines: 65,
        functions: 65,
        branches: 65,
        statements: 65,
      },
    },
  },
});