import { PropType } from '../gameplay/props/Prop';
import { PlayerData, LevelProgress } from '../core/SaveManager';
import { LevelCompletedData } from '../gameplay/LevelSystem';
import { Block } from '../gameplay/Block';
import { GameEvents } from './GameEvents';

export interface EventPayloadMap {
  [GameEvents.BLOCK_MERGED]: {
    newValue: number;
    position: { x: number; y: number };
    chainCount: number;
    newBlock: Block;
    destroyedBlocks: Block[];
  };
  [GameEvents.BLOCK_DROPPED]: void;
  [GameEvents.GAME_OVER]: void;
  [GameEvents.GAME_TIMEOUT]: void;
  [GameEvents.LEVEL_COMPLETED]: LevelCompletedData;
  [GameEvents.LEVEL_TIME_UPDATE]: number;
  [GameEvents.LEVEL_UNLOCKED]: number;
  [GameEvents.LEVEL_PROGRESS_UPDATED]: { levelId: number; progress: LevelProgress };
  [GameEvents.UI_START_GAME]: void;
  [GameEvents.UI_SELECT_LEVEL]: void;
  [GameEvents.UI_PAUSE]: void;
  [GameEvents.UI_RESUME]: void;
  [GameEvents.UI_RESTART]: void;
  [GameEvents.UI_BACK_TO_MENU]: void;
  [GameEvents.UI_NEXT_LEVEL]: void;
  [GameEvents.UI_LEVEL_SELECT]: void;
  [GameEvents.UI_REVIVE]: void;
  [GameEvents.UI_PROP_TARGET_MODE]: { type?: PropType; enabled: boolean };
  [GameEvents.UI_SETTINGS]: void;
  [GameEvents.UI_SETTINGS_CLOSED]: void;
  [GameEvents.UI_BUTTON_CLICK]: void;
  [GameEvents.PROPS_BOMB_EXPLODE]: { x: number; y: number; radius: number };
  [GameEvents.PROPS_BOMB_REQUIRE_TARGET]: void;
  [GameEvents.PROPS_FREEZE_ACTIVATED]: { duration: number };
  [GameEvents.PROPS_FREEZE_DEACTIVATED]: void;
  [GameEvents.PROPS_FREEZE_EXTENDED]: { additionalDuration: number };
  [GameEvents.PROPS_RAINBOW_ACTIVATED]: { remainingBlocks: number };
  [GameEvents.PROPS_RAINBOW_CONSUMED]: { remainingBlocks: number };
  [GameEvents.PROPS_RAINBOW_DEACTIVATED]: void;
  [GameEvents.PROPS_SHRINK_ACTIVATE]: { factor: number; duration: number };
  [GameEvents.PROPS_SHRINK_DEACTIVATE]: void;
  [GameEvents.PROPS_LUCKY_ACTIVATE]: { multiplier: number; remainingDrops: number };
  [GameEvents.PROPS_LUCKY_DEACTIVATE]: void;
  [GameEvents.PROPS_LUCKY_DROP_CONSUMED]: { remainingDrops: number };
  [GameEvents.PROPS_USED]: { type: PropType; remaining: number };
  [GameEvents.PROPS_USE_FAILED]: { type: PropType; reason: string };
  [GameEvents.PROPS_INITIALIZED]: { props: { type: PropType; count: number; maxCount: number }[] };
  [GameEvents.PROPS_RESET]: void;
  [GameEvents.GAMEPLAY_NEXT_BLOCK]: { isRainbow: boolean; remaining: number };
  [GameEvents.OBSTACLE_CLEARED]: void;
  [GameEvents.SCORE_UPDATED]: {
    totalScore: number;
    earnedScore: number;
    chainCount: number;
    baseScore: number;
    chainMultiplier: number;
  };
  [GameEvents.SCORE_CHAIN_ENDED]: void;
  [GameEvents.WARNING_STARTED]: void;
  [GameEvents.WARNING_ENDED]: void;
  [GameEvents.TUTORIAL_COMPLETED]: void;
  [GameEvents.SAVE_LOADED]: PlayerData;
  [GameEvents.SAVE_SAVED]: PlayerData;
  [GameEvents.SAVE_RESET]: PlayerData;
  [GameEvents.SAVE_IMPORTED]: PlayerData;
  [GameEvents.STARS_EARNED]: number;
  [GameEvents.COINS_CHANGED]: number;
  [GameEvents.DIAMONDS_CHANGED]: number;
  [GameEvents.SETTINGS_CHANGED]: PlayerData['settings'];
  [GameEvents.ACHIEVEMENT_UNLOCKED]: string;
  [GameEvents.SKIN_UNLOCKED]: string;
  [GameEvents.TALENT_UNLOCKED]: string;
  [GameEvents.AUDIO_MUTE_CHANGED]: { isMuted: boolean };
  [GameEvents.LEVEL_OBJECTIVE_DISMISSED]: void;
}
